---

name: docker

"on":
  push:
    paths:
      - '.github/dockerfiles/**'
    branches:
      - master
  pull_request:
    paths:
      - '.github/dockerfiles/**'

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -f .github/dockerfiles/java/Dockerfile -t ci .
      - name: Build
        run: docker run -t ci ./gradlew build -x test -x detekt

  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -f .github/dockerfiles/gradle/Dockerfile -t ci .
      - name: Build
        run: docker run -t ci gradle build -x test -x detekt
