---

name: release

"on":
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: 'tkfm'
  JAVA_VERSION: '17'
  JAVAFX_VERSION: '17'

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_name: windows
            archive_cmd: 7z a
            artifact_ext: .zip
            entrypoint_script_ext: .bat

          - os: macOS-latest
            os_name: osx
            archive_cmd: tar czf
            artifact_ext: .tar.gz
            entrypoint_script_ext: ''

          - os: ubuntu-latest
            os_name: linux
            archive_cmd: tar czf
            artifact_ext: .tar.gz
            entrypoint_script_ext: ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.8.0
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          java-package: jdk
          architecture: x64

      - name: Set build version information
        run: |
          echo ORG_GRADLE_PROJECT_CI_VERSION="${GITHUB_REF##*/v}" >> $GITHUB_ENV
          echo ORG_GRADLE_PROJECT_CI_COMMIT_HASH="$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew build -x test -x detekt

      - name: Create artifact
        run: >
          OS_NAME="${{ matrix.os_name }}"
          ARCHIVE_CMD="${{ matrix.archive_cmd }}"
          ARTIFACT_EXT="${{ matrix.artifact_ext }}"
          ENTRYPOINT_SCRIPT_EXT="${{ matrix.entrypoint_script_ext }}"
          VERSION="${ORG_GRADLE_PROJECT_CI_VERSION}"
          ./script/create_artifact.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/${{ env.APP_NAME }}_*.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
