---

name: release

"on":
  push:
    tags:
      - 'v*.*.*'

env:
  APP_NAME: 'tkfm'
  JAVA_VERSION: '16'
  JAVAFX_VERSION: '16'

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: jdk
          architecture: x64
      - name: Build
        run: >
          ORG_GRADLE_PROJECT_CI_VERSION="${GITHUB_REF##*/}"
          ORG_GRADLE_PROJECT_CI_COMMIT_HASH="$(git rev-parse HEAD)"
          ./gradlew build -x test

      - name: Create artifact
        run: |
          case ${{ matrix.os }} in
            windows-latest)
              os_name=windows
              ;;
            macOS-latest)
              os_name=osx
              ;;
            ubuntu-latest)
              os_name=linux
              ;;
          esac

          echo "os_name = $os_name"
          mkdir -p jmods/${os_name}
          curl -o jmods/${os_name}/jmods.zip -sSL https://download2.gluonhq.com/openjfx/${{ env.JAVAFX_VERSION }}/openjfx-${{ env.JAVAFX_VERSION }}_${os_name}-x64_bin-jmods.zip
          pushd jmods/${os_name}
          unzip jmods.zip
          popd
          ORG_GRADLE_PROJECT_CI_JMODS_DIR="jmods/${os_name}/javafx-jmods-${{ env.JAVAFX_VERSION }}" ./gradlew jlink
          mkdir ${{ env.APP_NAME }}_${os_name}
          cp -r .github/dist/* LICENSE build/libs/${{ env.APP_NAME }}-*.jar jre ${{ env.APP_NAME }}_${os_name}/
          mkdir dist
          case "$os_name" in
            windows)
              sed -i "s/{tag}/${GITHUB_REF##*/}/g" ${{ env.APP_NAME }}_${os_name}/${{ env.APP_NAME }}.bat
              7z a ${{ env.APP_NAME }}_${os_name}.zip ${{ env.APP_NAME }}_${os_name}
              mv ${{ env.APP_NAME }}_${os_name}.zip dist/
              ;;
            osx)
              sed -i '' "s/{tag}/${GITHUB_REF##*/}/g" ${{ env.APP_NAME }}_${os_name}/${{ env.APP_NAME }}
              tar czf ${{ env.APP_NAME }}_${os_name}.tar.gz ${{ env.APP_NAME }}_${os_name}
              mv ${{ env.APP_NAME }}_${os_name}.tar.gz dist/
              ;;
            linux)
              sed -i "s/{tag}/${GITHUB_REF##*/}/g" ${{ env.APP_NAME }}_${os_name}/${{ env.APP_NAME }}
              tar czf ${{ env.APP_NAME }}_${os_name}.tar.gz ${{ env.APP_NAME }}_${os_name}
              mv ${{ env.APP_NAME }}_${os_name}.tar.gz dist/
              ;;
          esac
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/${{ env.APP_NAME }}_*.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
