---

name: test

"on":
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - 'docs/*'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.*'
      - 'docs/*'

env:
  APP_NAME: 'tkfm'
  JAVA_VERSION: '16'
  JAVAFX_VERSION: '16'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-package: jdk
          architecture: x64
      - name: Install xvfb
        run: sudo apt install -y xvfb
      - name: Test
        run: xvfb-run ./gradlew test
      - name: Send coverage report
        run: bash <(curl -s https://codecov.io/bash)
